spring:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/underdogs
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: eu-west-3
      sqs:
        endpoint: http://localhost:4566