apiVersion: v1
kind: ConfigMap
metadata:
  name: underdogs-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "underdogs"
  JWT_ISSUER_URI: "http://keycloak-service:8080/realms/underdogs"
  JWT_JWK_SET_URI: "http://keycloak-service:8080/realms/underdogs/protocol/openid-connect/certs"
  CORS_ALLOWED_ORIGINS: "https://ton-domaine-frontend.com"
  SPRING_PROFILES_ACTIVE: "prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: underdogs-secrets
type: Opaque
data:
  # Valeurs encodées en Base64 (ex: admin -> YWRtaW4=)
  DB_USERNAME: YWRtaW4= # "admin" par exemple
  DB_PASSWORD: YWRtaW4= # "admin" par exemple