-- 1. Create a test user (Synchronized with Keycloak)
-- Note: The external_auth_id must match the ID (UUID) generated by Keycloak
INSERT INTO users (technical_id, external_auth_id, username, email, birth_date, first_name, last_name, kibbles_balance, role, created_at, updated_at, status, blocked_reason, id)
VALUES (1, '9b11db18-1b77-4cf3-94c5-34fb81de5a70', 'underdogs_fan', 'fan@underdogs.com', '1999-01-01', 'Jean', 'Dupont', 5000, 'USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVE', NULL, 'usr_001'),
       (2, 'a123db18-2b77-4cf3-84c5-44fb81de5a81', 'admin_user', 'admin@underdogs.com', '1990-05-15', 'Alice', 'Admin', 999999, 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVE', NULL, 'usr_002');

-- 2. Create a Tournament
INSERT INTO tournaments (technical_id, name, game, start_date, end_date, id)
VALUES (1, 'Underdogs Summer Split 2026', 'LEAGUE_OF_LEGENDS', '2026-06-01', '2026-08-31', 'trn_001');

-- 3. Create Teams
INSERT INTO teams (technical_id, name, tag, game, id)
VALUES (1, 'Karmine Corp', 'KC', 'LEAGUE_OF_LEGENDS', 'tm_001'),
       (2, 'G2 Esports', 'G2', 'LEAGUE_OF_LEGENDS', 'tm_002');

-- 4. Create Players (Linked to teams)
INSERT INTO players (technical_id, nickname, full_name, role, country_code, team_technical_id, id)
VALUES (1, 'Targamas', 'Raphaël Crabbé', 'SUPPORT', 'BE', 1, 'pl_001'),
       (2, 'Caps', 'Rasmus Winther', 'MID', 'DK', 2, 'pl_002');

-- 5. Create a Match (Linked to tournament and teams)
INSERT INTO matches (technical_id, team1_technical_id, team2_technical_id, tournament_technical_id, game, scheduled_at, status, team1_score, team2_score, live_started_at, winner_technical_id, id)
VALUES (1, 1, 2, 1, 'LEAGUE_OF_LEGENDS', '2026-07-30 18:00:00', 'SCHEDULED', NULL, NULL, NULL, NULL, 'mtc_001'),
       (2, 2, 1, 1, 'LEAGUE_OF_LEGENDS', '2026-07-20 18:00:00', 'COMPLETED', 1, 0, '2026-07-20 18:00:00', 2, 'mtc_002');

-- 6. Create a Bet (Linked to user, match, and selected team)
INSERT INTO bets (technical_id, user_technical_id, match_technical_id, selected_team_technical_id, amount, status, created_at, resolved_at, coefficient, potential_gain, id)
VALUES (1, 1, 1, 1, 100, 'PENDING', CURRENT_TIMESTAMP, NULL, 1.85, 185, 'bet_001');

-- WARNING: If using Hibernate Sequences (e.g., @GeneratedValue(strategy = GenerationType.SEQUENCE))
-- You must adjust the sequence to prevent ID conflicts during the first API insertion.
-- If using PostgreSQL with Hibernate-generated sequences, uncomment this and adjust the sequence name:
-- ALTER SEQUENCE users_seq RESTART WITH 50;
-- ALTER SEQUENCE teams_seq RESTART WITH 50;