-- The JPA entities declare @GeneratedValue(strategy = IDENTITY): Hibernate omits
-- technical_id from its INSERT statements and expects the database to supply it.
-- V1 created those columns as plain BIGINT, which made every insert fail.
--
-- BY DEFAULT rather than ALWAYS: an explicit value is still accepted, which the
-- existing data migrations rely on.

ALTER TABLE users ALTER COLUMN technical_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tournaments ALTER COLUMN technical_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE teams ALTER COLUMN technical_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE players ALTER COLUMN technical_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE matches ALTER COLUMN technical_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE bets ALTER COLUMN technical_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- The seed data occupies ids 1 and 2, so the sequences start beyond it to avoid
-- a collision on the first insert made by the application.
ALTER TABLE users ALTER COLUMN technical_id RESTART WITH 100;
ALTER TABLE tournaments ALTER COLUMN technical_id RESTART WITH 100;
ALTER TABLE teams ALTER COLUMN technical_id RESTART WITH 100;
ALTER TABLE players ALTER COLUMN technical_id RESTART WITH 100;
ALTER TABLE matches ALTER COLUMN technical_id RESTART WITH 100;
ALTER TABLE bets ALTER COLUMN technical_id RESTART WITH 100;
